### ISSUE TITLE
Pintout and voltages from RJ45 port on POW-HVM3.2H-24V-N

### ISSUE THREAD

**Issue by Oxmaster** [leodesigner/powmr_comm#12]
I've got POW-HVM3.2H-24V-N, still waiting for the batteries, so testing it with benchtop power supply.
![IMG_20240321_183427](https://github.com/odya/esphome-powmr-hybrid-inverter/assets/3867507/58914744-0c52-46ea-b2b8-839e73ff5d40)

I'm checking the RJ45 pinout on my bench and I'm getting different outputs than from the diagram provided. 

![rj45](https://github.com/odya/esphome-powmr-hybrid-inverter/assets/3867507/5cdf9082-5efd-4747-a5cf-02ea51d639b6)

White green (1) is GND
Brown (8) is + VBat 24 V
Blue (4) is + 13.2 V

or at least that's what my multimeter says. Don't want to remove the top cover because of the tamper seal to check for the RJ45 board.

**Comment by leodesigner** [comment]
Maybe you got a new version. Please check twice before connecting anything.
